app = "py-netgames-server"
kill_signal = "SIGTERM"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.http_checks]]
    path = "/health"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443